### ISSUE TITLE
Container extended_doc_db always using 5432 port

### ISSUE THREAD

**Issue by yannlaurickabe** [MEPP-team/UDV-server#73]
In the [config file](https://github.com/MEPP-team/UDV-server/blob/master/API_Enhanced_City/docker-compose.yml) of the container extend_doc_db, the current implementation chooses to automatically start it (line `restart: always`), which is in fact a good way to avoid several bugs using it.

_However_, that means that even if we do not need this container, it uses the 5432 port, then compels us to "free" this port by running a few commands (**listed below**) before being able to start a new container using it.

Especially when we want to work with the 3DCityDB container, we face this problem in a systematic way.

```
sudo docker container ls
sudo docker container stop extended_doc_db
```
---

**Suggestion** (cf. [container documentation](https://docs.docker.com/config/containers/start-containers-automatically/)):
```
# Instead of this :
restart: always

# We could try this :
restart: unless-stopped
```

**Comment by jailln** [comment]
Closed via #76 .
